export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
// import { ADD_NEW_EDUCATION } from './actionTypes';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_NEW_EXPERIENCE = 'ADD_NEW_EXPERIENCE'
export const UPDATE_EDUCATION = "UPDATE_EDUCATION"
export const UPDATE_SKILLS = "UPDATE_SKILLS"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const ADD_NEW_EDUCATION = "ADD_NEW_EDUCATION"
export const ADD_NEW_SKILLS = "ADD_NEW_SKILLS"
export const DELETE_EXPERIENCE = "DELETE_EXPERIENCE";
export const DELETE_EDUCATION = 'DELETE_EDUCATION';
export const DELETE_SKILLS = 'DELETE_SKILLS';
export const ADD_ADDITIONAL_INFOS = 'ADD_ADDITIONAL_INFOS';
export const ADD_ACHIEVEMENT = "ADD_ACHIEVEMENT";
export const UPDATE_ACHIEVEMENT = "UPDATE_ACHIEVEMENT";
export const DELETE_ACHIEVEMENT = "DELETE_ACHIEVEMENT";

export const ADD_CERTIFICATE = "ADD_CERTIFICATE";
export const UPDATE_CERTIFICATE = "UPDATE_CERTIFICATE";
export const DELETE_CERTIFICATE = "DELETE_CERTIFICATE";

