export const UPDATE_PERSONAL_INFO = 'UPDATE_PERSONAL_INFO';
export const ADD_EXPERIENCE = 'ADD_EXPERIENCE';
export const ADD_NEW_EXPERIENCE = 'ADD_NEW_EXPERIENCE'
export const UPDATE_EDUCATION = "UPDATE_EDUCATION"
export const UPDATE_SKILLS = "UPDATE_SKILLS"
export const ADD_EDUCATION = "ADD_EDUCATION"
export const ADD_NEW_EDUCATION = "ADD_NEW_EDUCATION"
export const ADD_NEW_SKILLS = "ADD_NEW_SKILLS"
